export const CLICK_MENU_BUTTON = 'CLICK_MENU_BUTTON';
export const CHANGE_SEARCHBOX_INPUT = 'CHANGE_SEARCHBOX_INPUT';
export const MOUNT_ITEMS_TO_RENDER = 'MOUNT_ITEMS_TO_RENDER';

export const REQUEST_MENU_PENDING = 'REQUEST_MENU_PENDING';
export const REQUEST_MENU_SUCCESS = 'REQUEST_MENU_SUCCESS';
export const REQUEST_MENU_FAILED = 'REQUEST_MENU_FAILED';

export const REQUEST_ITEMS_PENDING = 'REQUEST_ITEMS_PENDING';
export const REQUEST_ITEMS_SUCCESS = 'REQUEST_ITEMS_SUCCESS';
export const REQUEST_ITEMS_FAILED = 'REQUEST_ITEMS_FAILED';

export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';

export const REQUEST_HOMEWORLD_PENDING = 'REQUEST_HOMEWORLD_PENDING';
export const REQUEST_HOMEWORLD_SUCCESS = 'REQUEST_HOMEWORLD_PENDING';
export const REQUEST_HOMEWORLD_FAILED = 'REQUEST_HOMEWORLD_PENDING';